version: '3.9'
services:
  db:
    image: mysql:8
    container_name: star-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+09:00
    volumes:
      - star-dbdata:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    restart: always
    networks:
      - star-network
    profiles:
      - prod
      - dev

  server-dev:
    build:
      context: ./
      target: development
    container_name: star-server
    restart: always
    working_dir: /usr/src/app
    volumes:
      - star-appdata:/usr/src/app
      - star-nodedata:/usr/src/app/node_modules
      - ./src:/usr/src/app/src
    ports:
      - ${APP_HOST_PORT_DEV}:${APP_CONTAINER_PORT}
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db:${DB_CONTAINER_PORT} -t 15 && yarn start:dev
    networks:
      - star-network
    profiles:
      - dev

  server-prod:
    build:
      context: ./
      target: production
    container_name: star-server-prod
    restart: always
    working_dir: /usr/src/app
    volumes:
      - star-appdata:/usr/src/app
    ports:
      - ${APP_HOST_PORT_PROD}:${APP_CONTAINER_PORT}
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db:${DB_CONTAINER_PORT} -t 15 && yarn start:prod
    networks:
      - star-network
    profiles:
      - prod

networks:
  star-network:
    driver: bridge

volumes:
  star-dbdata:
    driver: local
  star-appdata:
    driver: local
  star-nodedata:
    driver: local
