version: '3.8'
services:
  db:
    image: mysql:8
    container_name: nestjs-star-loc-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+09:00
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    restart: always
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  dbdata:
    driver: local
