version: '3.9'
services:
  db:
    image: mysql:8
    container_name: star-dev-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+09:00
    volumes:
      - star-dbdata-dev:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    restart: always
    networks:
      - star-network-dev
  server:
    build:
      context: ./
    container_name: star-server-dev
    restart: always
    working_dir: /usr/src/app
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - ${APP_HOST_PORT_DEV}:${APP_CONTAINER_PORT}
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db:${DB_CONTAINER_PORT} -t 15
        yarn start:dev
    networks:
      - star-network-dev
networks:
  star-network-dev:
    driver: bridge
volumes:
  star-dbdata-dev:
    driver: local
